# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.TextField(default=None, null=True)),
                ('post_pic', models.FileField(default=None, null=True, upload_to='')),
                ('post_video', models.FileField(default=None, null=True, upload_to='')),
                ('post_doc', models.FileField(default=None, null=True, upload_to='')),
                ('post_file', models.FileField(default=None, null=True, upload_to='')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('tag_no', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('post', models.ManyToManyField(to='postfeed.Post')),
            ],
        ),
    ]
