# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postfeed', '0002_auto_20170905_2350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('text',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('tag',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_doc',
            new_name='pic',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_pic',
            new_name='video',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_video',
        ),
        migrations.AlterField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(blank=True, to='postfeed.Post'),
        ),
    ]
