# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postfeed', '0003_auto_20171003_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
    ]
