# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 09:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postfeed', '0006_auto_20171028_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(blank=True, null=True, to='postfeed.Post'),
        ),
        migrations.AlterField(
            model_name='userprefernces',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='postfeed.Tag'),
        ),
        migrations.AlterField(
            model_name='userprefernces',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
