# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profile_picture',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
