# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 04:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_userinfo_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_picture',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
