# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20171003_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
