# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_del', models.BooleanField(default=False)),
                ('sender_trash', models.BooleanField(default=False)),
                ('mail_sub', models.CharField(blank=True, max_length=100, null=True)),
                ('mail_body', models.TextField(blank=True, null=True)),
                ('receiver_del', models.BooleanField(default=False)),
                ('receiver_trash', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
