# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinionpoll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollchoice',
            name='poll_count',
            field=models.IntegerField(default=0),
        ),
    ]
