# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinionpoll', '0002_pollchoice_poll_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollquestion',
            name='no_of_choices',
            field=models.IntegerField(default=2),
        ),
    ]
