# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opinionpoll', '0003_pollquestion_no_of_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollchoice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opinionpoll.PollQuestion'),
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='no_of_choices',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
