# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 10:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opinionpoll', '0004_auto_20170831_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollquestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='voted',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
